name: Wavelit builds
on: [push, pull_request]
jobs:
  build:
    name: Wavelit on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3

      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.1'
          java-version: '19'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Run tests
        run: |
          ./gradlew test

      - name: Build native
        run: |
          ./gradlew app:nativeCompile

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: wavelit-${{ matrix.os }}
          path: ./app/build/native/nativeCompile/wavelit
...
